### ISSUE TITLE
Cuando se ponga en producción habrá que revisar los enlaces a 'hacklab-almeria.github.io' para que apunten a 'hacklabalmeria.net'

### ISSUE THREAD

**Issue by josejuansanchez** [HackLab-Almeria/hacklab-almeria.github.io#10]

**Comment by MiguelAngelLV** [comment]
¿Hay alguna manera de configurar para que el {{site.url}} apunte al dominio que quieras?

**Comment by josejuansanchez** [comment]
Para el `atom.xml` he utilizado `site.domain`, pero he ceado esta _issue_ porque creo que en el template hay algunos enlaces que están puestos directamente y no utilizan este valor.

Habría que revisar el template y hacer que usasen las variables de configuración.
