### ISSUE TITLE
No debería aparecer '%' antes de 'KB'

### ISSUE THREAD

**Issue by jorgesumle** [HackLab-Almeria/hacklab-almeria.github.io#113]
![screenshot from 2016-09-08 23-57-42](https://cloud.githubusercontent.com/assets/14212780/18368449/4bf3273e-7620-11e6-9c2c-aa5b4a8243bc.png)

**Comment by olea** [comment]
No entiendo. ¿Dónde ocurre eso?

**Comment by jorgesumle** [comment]
Cuando intentas subir una imagen muy grande aparece ese mensaje.

**Comment by olea** [comment]
Pero nuestra web no tiene forma de subir ficheros si no es a través de git.

:-???

**Comment by jorgesumle** [comment]
Si subes la imagen en una respuesta a un tema, sí.

**Comment by olea** [comment]
Hijo, tú no estás hablando de nuestra web. Tú estás hablando del foro y el foro es [Discourse](https://www.discourse.org/).

En fin.

**Comment by jorgesumle** [comment]
Antes de cerrarlo habrá que arreglarlo, digo yo.

**Comment by olea** [comment]
> Antes de cerrarlo habrá que arreglarlo, digo yo.

Go For It: https://github.com/discourse/discourse

**Comment by jorgesumle** [comment]
¡Listo!
![screenshot from 2016-09-12 22-56-45](https://cloud.githubusercontent.com/assets/14212780/18452733/6ac983dc-793c-11e6-9506-c9f2953094b5.png)
