### ISSUE TITLE
Licencia?

### ISSUE THREAD

**Issue by jorgesumle** [HackLab-Almeria/hacklab-almeria.github.io#117]
> © Los respectivos autores, 2015, 2016.
> Licencia Attribution 4.0 International (CC BY 4.0)

Esto se refiere al contenido de los autores de cada post, vale, ¿pero y el código? Una buena práctica es especificar qué contenido está bajo qué licencia (e.g. https://github.com/unknown-horizons/unknown-horizons#license).

**Comment by olea** [comment]
No. Obviamente se refiere a todo.

**Comment by jorgesumle** [comment]
Allá tú. Puedes leer en las FAQ de Creative Commons que su licencia no está hecha para software y recomiendan que no se use para eso: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

> No. Obviamente se refiere a todo.

No, obviamente, no se refiere al software, porque no está hecha para el software. Lo estás haciendo mal.

Solo dicen que tiene validez la CC0, o dominio público, que no es el caso de este proyecto: https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F

**Comment by olea** [comment]
Allá yo. Sí.
