### ISSUE TITLE
Añadir "Ley de Cookies"

### ISSUE THREAD

**Issue by zerasul** [HackLab-Almeria/hacklab-almeria.github.io#13]
Añadir el Texto de la Ley de Cookies y el Aviso Legal.

**Comment by MiguelAngelLV** [comment]
Si no hay cookies no hay que poner aviso.

En el único sitio dónde se ponen cookies será en el foro, pero creo que
solo hay que ponerlo si es de rastreo / publicidad y demás, y no es el caso.

2015-02-23 12:25 GMT+01:00 Victor Suarez <notifications@github.com>:

> Añadir el Texto de la Ley de Cookies y el Aviso Legal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/13>.
>



-- 
Miguel Ángel López

**Comment by MiguelAngelLV** [comment]
Jums, estoy releyendo y parece que cualquier tipo de cookie obliga a poner
la maldita ley, incluida la de los foros o el google analytics...

2015-02-23 12:30 GMT+01:00 José Juan Sánchez <notifications@github.com>:

> Closed #13
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/13>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/13#event-240065985>
> .
>



-- 
Miguel Ángel López

**Comment by MiguelAngelLV** [comment]
Me resquetespondo: Las cookies técnicas (como las del foro) son aceptadas y
no requieren el aviso, pero el Analytics sí:

http://www.bonillaware.com/cumplir-ley-de-cookies-y-analytics

El 23 de febrero de 2015, 12:34, Miguel Ángel López Vicente <
miguel.angel.lopez.vicente@gmail.com> escribió:

> Jums, estoy releyendo y parece que cualquier tipo de cookie obliga a poner
> la maldita ley, incluida la de los foros o el google analytics...
>
> 2015-02-23 12:30 GMT+01:00 José Juan Sánchez <notifications@github.com>:
>
>> Closed #13
>> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/13>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/13#event-240065985>
>> .
>>
>
>
>
> --
> Miguel Ángel López
>



-- 
Miguel Ángel López

**Comment by josejuansanchez** [comment]
Habría que actualizar la URL que se se muestra cuando se pincha sobre *Más información*.
Actualmente apunta a http://example.com

**Comment by zerasul** [comment]
Cuando esté hecha la página de aviso legal se añadirá ahí.
