### ISSUE TITLE
Incluir pasos para instalar en Mac OS X

### ISSUE THREAD

**Issue by valgreens** [HackLab-Almeria/hacklab-almeria.github.io#14]
Se podría añadir también los pasos de instalación en Mac junto con GNU/Linux y Windows

**Comment by zerasul** [comment]
No te preocupes esta tarde lo instalo en mi Mac y Lo añado al README. Es que claro aquí MIguel diría que no quiere a los de Mac Aquí...

**Comment by valgreens** [comment]
Si tengo tiempo lo hago yo, no hay problema!

**Comment by josejuansanchez** [comment]
@valgreens Perfect! :)

**Comment by MiguelAngelLV** [comment]
Yo no lo he puesto porque no sé cómo es. Entiendo que será parecido a Linux.

**Comment by baldboy** [comment]
No se si estáis hablando de instalar jekyll, yo lo tengo instalado en mi
mac y rulando con los pasos de la web sin problemas.
