### ISSUE TITLE
Incluir licencia en el repositorio y en la web

### ISSUE THREAD

**Issue by josejuansanchez** [HackLab-Almeria/hacklab-almeria.github.io#17]

**Comment by olea** [comment]
Hala, por (no) hablar

**Comment by olea** [comment]
¿Qué quiere decir «incluir licencia en el repositorio»?

**Comment by josejuansanchez** [comment]
@olea Indluir en el `README.md` bajo que tipo de licencia se libera el repositorio de la web y si es necesario añadir algún archivo al repositorio con la licencia escogida.

**Comment by olea** [comment]
Si te refieres al repo de la web la licencia sería la misma.

**Comment by josejuansanchez** [comment]
@olea Me refería a que hay que hacer varias cosas:
* Decidir la licencia.
* Actualizar el texto del `README.md`.
* Añadir un archivo con el texto de la licencia en el repositorio (si fuese necesario).
* Actualizar el pie de página de la web con la licencia escogida.

**Comment by olea** [comment]
2015-02-25 12:07 GMT+01:00 José Juan Sánchez <notifications@github.com>:

> @olea <https://github.com/olea> Me refería a que hay que hacer varias
> cosas:
>
>    - Decidir la licencia.
>    - Actualizar el texto del README.md.
>    - Añadir un archivo con el texto de la licencia en el repositorio (si
>    fuese necesario).
>    - Actualizar el pie de página de la web con la licencia escogida.
>
>  ¡ahora sí hablas como un ingeniero! :-D


-- 

Ismael Olea

http://olea.org/diario/
