### ISSUE TITLE
Mejorar la precisión de Sonar

### ISSUE THREAD

**Issue by jesmg** [HackLab-Almeria/hacklab-almeria.github.io#172]
Es necesario mejorar la precisión del informe de Sonar.

Que algún estudioso de la web me diga los directorios que no deberían ser analizados, y de cuales solo debería ser analizada una muestra.

**Comment by jesmg** [comment]
Precisión mejorada en #556d6fbba929a74a3e41aa0ee13f57d558e409d7

**Comment by JuanjoSalvador** [comment]
¿podemos cerrar esta issue entonces?

**Comment by jesmg** [comment]
Aun no, estaría mejor que me deis mas info para afinar mas

**Comment by JuanjoSalvador** [comment]
Pues a ver, Sonar detecta una vulnerabilidad en jQuery 1.11.2 (deprecated!).

**Comment by jesmg** [comment]
No confundir falsos positivos y mala gestión de dependencias x)

**Comment by JuanjoSalvador** [comment]
Pero eso debería actualizarse también.
