### ISSUE TITLE
¿Cuando se ponga la web en producción, la vamos a dejar en GitHub Pages o la vamos a alojar en el servidor actual?

### ISSUE THREAD

**Issue by josejuansanchez** [HackLab-Almeria/hacklab-almeria.github.io#18]
Para alojar la web en GitHub Pages sólo hay que seguir estos pasos:

* [Setting up a custom domain with GitHub Pages](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages)

**Comment by olea** [comment]
On Wed, Feb 25, 2015 at 12:03 PM, José Juan Sánchez <
notifications@github.com> wrote:

> Para alojar la web en GitHub Pages sólo hay que seguir estos pasos:
>
>    - Setting up a custom domain with GitHub Pages
>    <https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages>
>
>
pero esas instrucciones son para usar un subdominio.ejemplo.com y no
ejemplo.com, que es lo necesario.

el caso es  que juraría que he visto usar GH Pages para este caso pero no
he sabido encontrar la explicación (ni me he sentado a intentar probarlo a
lo bestia).

-- 

Ismael Olea

http://olea.org/diario/

**Comment by josejuansanchez** [comment]
Para un dominio se hace igual, yo lo tengo hecho así para mi web personal :)

**Comment by MiguelAngelLV** [comment]
Yo lo dejaría en GitHub: Servidor gratuito, fiable, sin publicidad y ya
está todo montado.

2015-02-25 12:12 GMT+01:00 José Juan Sánchez <notifications@github.com>:

> Para un dominio se hace igual, yo lo tengo hecho así para mi web personal
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/18#issuecomment-75943267>
> .
>



-- 
Miguel Ángel López

**Comment by zerasul** [comment]
Ahora es cuando salta Ruben.....

2015-02-25 12:19 GMT+01:00 Miguel Ángel López Vicente <
notifications@github.com>:

**Comment by olea** [comment]
On Wed, Feb 25, 2015 at 12:18 PM, Miguel Ángel López Vicente <
notifications@github.com> wrote:

> Yo lo dejaría en GitHub: Servidor gratuito, fiable, sin publicidad y ya
> está todo montado.
>

al menos yo no he dicho nada de cambiarlo, sólo de configurar el DNS :-m


-- 

Ismael Olea

http://olea.org/diario/

**Comment by zerasul** [comment]
Una cosa que yo haría es ir creando un subdominio. En plan old.hacklabalmeria.net o algo así para que cuando se cambie a la nueva web se pueda acceder a la vieja.

**Comment by olea** [comment]
2015-02-25 12:31 GMT+01:00 Victor Suarez <notifications@github.com>:

> Una cosa que yo haría es ir creando un subdominio. En plan
> old.hacklabalmeria.net o algo así para que cuando se cambie a la nueva
> web se pueda acceder a la vieja.
>

pídelo a @goretoxo (antes usábamos para eso el redmine).


pero por el amor de dios, que no sea un nombre en inglés.

-- 

Ismael Olea

http://olea.org/diario/

**Comment by MiguelAngelLV** [comment]
También hay que pedirle el cambio de los foros

El 25 de febrero de 2015, 12:42, Ismael Olea <notifications@github.com>
escribió:

> 2015-02-25 12:31 GMT+01:00 Victor Suarez <notifications@github.com>:
>
> > Una cosa que yo haría es ir creando un subdominio. En plan
> > old.hacklabalmeria.net o algo así para que cuando se cambie a la nueva
> > web se pueda acceder a la vieja.
> >
>
> pídelo a @goretoxo (antes usábamos para eso el redmine).
>
>
> pero por el amor de dios, que no sea un nombre en inglés.
>
> --
>
> Ismael Olea
>
> http://olea.org/diario/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/18#issuecomment-75946760>
> .
>



-- 
Miguel Ángel López

**Comment by olea** [comment]
2015-02-25 12:54 GMT+01:00 Miguel Ángel López Vicente <
notifications@github.com>:

> También hay que pedirle el cambio de los foros
>

y antes de eso: ¿el sitio definitivo del discourse será bitnami? ¿no hay
que pagar?


-- 

Ismael Olea

http://olea.org/diario/

**Comment by MiguelAngelLV** [comment]
En bitnami tenemos cuanta durante un año, pero  habría que ir buscando un
sistema alternativo. ¿Al final lo de pedir la VM al CICA como quedó?

El 25 de febrero de 2015, 13:04, Ismael Olea <notifications@github.com>
escribió:

> 2015-02-25 12:54 GMT+01:00 Miguel Ángel López Vicente <
> notifications@github.com>:
>
> > También hay que pedirle el cambio de los foros
> >
>
> y antes de eso: ¿el sitio definitivo del discourse será bitnami? ¿no hay
> que pagar?
>
>
>
> --
>
> Ismael Olea
>
> http://olea.org/diario/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/18#issuecomment-75949131>
> .
>



-- 
Miguel Ángel López

**Comment by olea** [comment]
2015-02-25 13:09 GMT+01:00 Miguel Ángel López Vicente <
notifications@github.com>:

> En bitnami tenemos cuanta durante un año, pero habría que ir buscando un
> sistema alternativo. ¿Al final lo de pedir la VM al CICA como quedó?
>

en que no me da la vida y se me pasó pedirlo.

también podría escribir al CEO de Bitnami a ver si se enrollara gratisware.

-- 

Ismael Olea

http://olea.org/diario/

**Comment by MiguelAngelLV** [comment]
También hay que cambiar el fichero CNAME al que corresponda

**Comment by MiguelAngelLV** [comment]
Todas las cosas cambiadas y parece que funcionando :)
