### ISSUE TITLE
Estilos de la web de Hacklab Almería en Https

### ISSUE THREAD

**Issue by zerasul** [HackLab-Almeria/hacklab-almeria.github.io#180]
He podido ver que si cargas la web (no el foro) por https, no cargan los estilos por que están referenciados por http y el navegador las bloquea.

Sería interesante poder referenciarlos a través de https o http en función de que URL estés viendo.

**Comment by JuanjoSalvador** [comment]
Según parece, esto lo podemos arreglar cambiando `{{ site.url }}` por `{{ root }}` y declarando la variable de entorno `root` en el `_config.yml`

Problema: hay que probarlo en producción, porque afecta directamente a Github Pages y SSL.
