### ISSUE TITLE
Caracter extraño en la actividad CCAlm

### ISSUE THREAD

**Issue by MiguelAngelLV** [HackLab-Almeria/hacklab-almeria.github.io#22]
Hay algún caracter raro o algo en [CCALM][1] pero no consigo identificarlo. El caso es que el Dicourse no crea la nueva entrada porque al pasear el HTML se topa con el caracter y falla. 

Y no, no muestra ni fila ni columna dónde se halla dicho caracter.

[1]: https://github.com/HackLab-Almeria/hacklab-almeria.github.io/blob/master/_posts/2015-03-26-CCAlm.md

**Comment by olea** [comment]
¿Pueden ser las comillas latinas «»?

2015-02-26 10:50 GMT+01:00 Miguel Ángel López Vicente <
notifications@github.com>:

> Hay algún caracter raro o algo en CCALM
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/blob/master/_posts/2015-03-26-CCAlm.md>
> pero no consigo identificarlo. El caso es que el Dicourse no crea la nueva
> entrada porque al pasear el HTML se topa con el caracter y falla.
>
> Y no, no muestra ni fila ni columna dónde se halla dicho caracter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/22>.
>



-- 

Ismael Olea

http://olea.org/diario/

**Comment by MiguelAngelLV** [comment]
Eso es lo primero que pensé y las quité, probé, y nada. Puedes ver que he
estado haciendo varios commits esta mañana sin éxito, a menos que se
quedase alguna suelta por ahí pero no me suena.

En este commit no he dejado nada raro y sigue dando el problema:
https://github.com/HackLab-Almeria/hacklab-almeria.github.io/blob/735efa3746ce14c93a49cf35ddd24adf51ac5712/_posts/2015-03-26-CCAlm.md

El 26 de febrero de 2015, 10:56, Ismael Olea <notifications@github.com>
escribió:

> ¿Pueden ser las comillas latinas «»?
>
> 2015-02-26 10:50 GMT+01:00 Miguel Ángel López Vicente <
> notifications@github.com>:
>
> > Hay algún caracter raro o algo en CCALM
> > <
> https://github.com/HackLab-Almeria/hacklab-almeria.github.io/blob/master/_posts/2015-03-26-CCAlm.md
> >
> > pero no consigo identificarlo. El caso es que el Dicourse no crea la
> nueva
> > entrada porque al pasear el HTML se topa con el caracter y falla.
> >
> > Y no, no muestra ni fila ni columna dónde se halla dicho caracter.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/22
> >.
> >
>
>
>
> --
>
> Ismael Olea
>
> http://olea.org/diario/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/22#issuecomment-76150718>
> .
>



-- 
Miguel Ángel López

**Comment by olea** [comment]
2015-02-26 11:04 GMT+01:00 Miguel Ángel López Vicente <
notifications@github.com>:

> Eso es lo primero que pensé y las quité, probé, y nada


he probado a guardar el fichero en otro formato (iso-*) y a la primera el
mismo jekyll se ha quejado:

Error reading file /home/olea/git/
hacklab-almeria.github.io/_posts/2015-03-26-CCAlm.md: invalid byte sequence
in UTF-8
...error:
             Error: invalid byte sequence in UTF-8
             Error: Run jekyll build --trace for more information.


luego lo he vuelto a grabar como antes y lo acepta tan pancho (y un git
dfff al final no ha sacado diferencias con el principio)

-- 

Ismael Olea

http://olea.org/diario/

**Comment by josejuansanchez** [comment]
Creo que el problema está en alguno de los layouts que tenemos.

Para comprobarlo he realizado una prueba creando un layout sencillo, con las mínimas etiquetas html necesarias, y he creado un post con un texto de prueba utilizando el layout anterior. Una vez hecho esto he lanzdo la tarea `Jobs::PollFeed` desde la adminstración de discourse y el post se ha insertado correctamente en el foro como una nueva actividad.

Luego he borrado el post del foro, he cambiado el layout del post de prueba con el layout `post` y he vuelto a lanzar la tarea `Jobs::PollFeed`, pero en esta ocasión la operación no ha tenido éxito y el post no se ha insertado en el foro.

Faltaría por probar qué pasaría si le asignamos a todos los post que tenemos el layout sencillo que ha funcionado en la primera prueba. Esto nos podría ayudar a confirmar que efectiamente el error está en los layouts.

**Comment by MiguelAngelLV** [comment]
Había tildes y todo eso?

**Comment by MiguelAngelLV** [comment]
Cerrado al fin.

El problema estaba en que Discourse, al leer el `atom.xml` fallaba si encontraba tildes o caracteres especiales en general en el título.

La solución ha sido modificar dicourse tal y como explico en este [post][1]:

[1]: https://www.google.com/url?q=https%3A%2F%2Fmeta.discourse.org%2Ft%2Fembed-poll-feed-fail-with-utf8-title%2F25776&sa=D&sntz=1&usg=AFQjCNHNYMAZNCYNybawRRrGIlPoLo4suw
