### ISSUE TITLE
añadir URI's al sitemap.xml

### ISSUE THREAD

**Issue by olea** [HackLab-Almeria/hacklab-almeria.github.io#27]
guardadas temporalmente en https://github.com/HackLab-Almeria/hacklab-almeria.github.io/blob/master/sitemap.txt

**Comment by MiguelAngelLV** [comment]
Estoy mirando el puglin de redirect de jekyll que parece compatible con GitHub para redigiri de los antiguos eventos a los nuevos

**Comment by josejuansanchez** [comment]
Todas las URLs enumeradas en `sitemap.xml` deben residir en el mismo host, por lo tanto no podemos incluir:
* http://redmine.hacklabalmeria.net
* http://foro.hacklabalmeria.net
* http://antigua.hacklabalmeria.net

Se ha actualizado el código para incluir las otras URLs que sí están en el mismo host.
