### ISSUE TITLE
Vista de actividades en formato de agenda

### ISSUE THREAD

**Issue by olea** [HackLab-Almeria/hacklab-almeria.github.io#29]
Hasta ahora hemos usado el calendario gCalendar como el directorio principal de actividades. Eso permite incluir fácilmente actividades programadas por terceros pero que creemos que encajan en nuestra comunidad sin que tengan asociada una página en nuestra web o nuestro foro.

Lo ideal sería poder tener una lista en formato agenda de dicho calendario (probablemente tanto en la portada como en http://hacklabalmeria.net/actividades/ ). A mi me parece que es información prioritaria.

**Comment by MiguelAngelLV** [comment]
Se puede poner `agenda` por defecto:

````html
<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=eohual6srvr2l4oqa1ujevad9s%40group.calendar.google.com&amp;color=%23B1365F&amp;ctz=Europe%2FMadrid" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>
````

Colócalo dónde quieras

**Comment by olea** [comment]
2015-03-01 19:17 GMT+01:00 Miguel Ángel López Vicente <
notifications@github.com>:

> Se puede poner agenda por defecto:
>
>
guay


-- 

Ismael Olea

http://olea.org/diario/

**Comment by MiguelAngelLV** [comment]
Closed by 8cd9e2945b52fdbf6d19bd499f87965b7183eefb
