### ISSUE TITLE
Añadir Enlace a "Web Antigua"

### ISSUE THREAD

**Issue by zerasul** [HackLab-Almeria/hacklab-almeria.github.io#31]
He estado pensando en añadir un botón más a la portada para que haya un enlace a la "Web Antigua"

**Comment by olea** [comment]
On Mon, Mar 2, 2015 at 10:12 AM, Victor Suarez <notifications@github.com>
wrote:

> He estado pensando en añadir un botón más a la portada para que haya un
> enlace a la "Web Antigua"
>
¿qué sentido tiene añadir ese enlace a la web antigua en la misma portada?

no aporta información, confunde/distrae al visitante y resta sencillez a la
portada.

yo creo que no merece la pena.

-- 

Ismael Olea

http://olea.org/diario/

**Comment by MiguelAngelLV** [comment]
Solo tiene sentido si pudiésemos detectar que es Rubén quien entra y que
solo lo vea él.

El 2 de marzo de 2015, 10:18, Ismael Olea <notifications@github.com>
escribió:

> On Mon, Mar 2, 2015 at 10:12 AM, Victor Suarez <notifications@github.com>
> wrote:
>
> > He estado pensando en añadir un botón más a la portada para que haya un
> > enlace a la "Web Antigua"
> >
> ¿qué sentido tiene añadir ese enlace a la web antigua en la misma portada?
>
> no aporta información, confunde/distrae al visitante y resta sencillez a la
> portada.
>
> yo creo que no merece la pena.
>
> --
>
> Ismael Olea
>
> http://olea.org/diario/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/31#issuecomment-76679698>
> .
>



-- 
Miguel Ángel López

**Comment by zerasul** [comment]
Yo lo veo al menos necesario ahora mismo para el tema de entrar al antiguo foro y tenerlo como archivo.

**Comment by olea** [comment]
2015-03-02 10:24 GMT+01:00 Victor Suarez <notifications@github.com>:

> Yo lo veo al menos necesario ahora mismo para el tema de entrar al antiguo
> foro y tenerlo como archivo.
>
el foro está accesible en http://hacklabalmeria.net/foro-nabble/
-- 

Ismael Olea

http://olea.org/diario/
