### ISSUE TITLE
Incluir los comentarios más recientes de Discourse en la portada

### ISSUE THREAD

**Issue by josejuansanchez** [HackLab-Almeria/hacklab-almeria.github.io#6]
Referencia: 
* http://eviltrout.com/2014/01/22/embedding-discourse.html

**Comment by MiguelAngelLV** [comment]
El problema es que parece estar pensado para crear un hilo de comentario
por post, por ejemplo, en cada página de eventos podríamos incluir un
sistema de comentarios que en realidad sería un hilo en sí.

Tendríamos que mirar la API y tirar de JS para incluir los últimos temas. O
algo así.

2015-02-23 9:52 GMT+01:00 José Juan Sánchez <notifications@github.com>:

> Referencia:
>
>    - http://eviltrout.com/2014/01/22/embedding-discourse.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HackLab-Almeria/hacklab-almeria.github.io/issues/6>.
>



-- 
Miguel Ángel López

**Comment by MiguelAngelLV** [comment]
La documentación de la API está aquí: https://meta.discourse.org/t/discourse-api-documentation/22706

La verdad es que es muy sencilla, un para de JSON's y poco más. Ya sería cuestión de hacer un javascript que lo consulte, porque dudo que podamos hacerlo mediante Jekyll, ¿no? Entiendo que Jekyll se ejecuta solo cuando hay cambios en los ficheros.

**Comment by MiguelAngelLV** [comment]
Otra opción es usar los RSS `http://discourse.hacklabalmeria.bitnamiapp.com/latest.rss`

**Comment by zerasul** [comment]
Ya se muestran en portada los mensajes.
