### ISSUE TITLE
Crear RSS de los eventos

### ISSUE THREAD

**Issue by MiguelAngelLV** [HackLab-Almeria/hacklab-almeria.github.io#7]
He visto que hay plugins para _Jekyll_ para crear `RSS` de lost _posts_, o eventos en nuestro caso.

Sería cuestión de integrarlos: https://github.com/agelber/jekyll-rss

**Comment by josejuansanchez** [comment]
Al esta utilizando _GitHub Pages_ no tenemos la posibilidad de instalar puglins de terceros, tenemos que utilizar los que ellos nos proporcionan.

Aquí hay más info:
* https://help.github.com/articles/using-jekyll-plugins-with-github-pages/
* https://pages.github.com/versions/

De todos se puede hacer sin utilizar un plugin. Yo me encargo de esta issue.
